USE soupi_db; 

CREATE TABLE [TASK] (
	[Id] INTEGER NOT NULL IDENTITY UNIQUE,
	[Name] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(255),
	[CreatorId] INTEGER NOT NULL,
	[AssigneeId] INTEGER NOT NULL,
	[ParentTaskId] INTEGER,
	[Status] NVARCHAR(255) NOT NULL DEFAULT '0',
	[TimeCost] TIME,
	[ProjectId] INTEGER NOT NULL,
	[StartTime] DATETIME,
	[EndTime] DATETIME,
	PRIMARY KEY([Id])
);
GO

CREATE TABLE [NOTIFICATION] (
	[Id] INTEGER NOT NULL IDENTITY UNIQUE,
	[RecieverId] INTEGER NOT NULL,
	[SenderId] INTEGER NOT NULL,
	[Text] NVARCHAR(255) NOT NULL,
	[Link] NVARCHAR(255) NOT NULL,
	PRIMARY KEY([Id])
);
GO

CREATE TABLE [USER] (
	[Id] INTEGER NOT NULL IDENTITY UNIQUE,
	[Name] NVARCHAR(255) NOT NULL UNIQUE,
	[GithubUser] NVARCHAR(255),
	[Image] NVARCHAR(255),
	PRIMARY KEY([Id])
);
GO

CREATE TABLE [PROJECT] (
	[Id] INTEGER NOT NULL IDENTITY UNIQUE,
	[Name] NVARCHAR(255) NOT NULL UNIQUE,
	[GithubRepository] NVARCHAR(255),
	[CreatorId] INTEGER NOT NULL,
	[Image] NVARCHAR(255),
	PRIMARY KEY([Id])
);
GO

CREATE TABLE [TEAM_MEMBER] (
	[Id] INTEGER NOT NULL IDENTITY UNIQUE,
	[UsedId] INTEGER NOT NULL,
	[ProjectId] INTEGER NOT NULL,
	[Role] NVARCHAR(255),
	[ManagerId] INTEGER,
	PRIMARY KEY([Id])
);
GO

CREATE TABLE [TASK_SEQUENCE] (
	[PreceedingTaskId] INTEGER NOT NULL,
	[SubsequentTaskId] INTEGER NOT NULL,
	PRIMARY KEY([PreceedingTaskId], [SubsequentTaskId])
);
GO


ALTER TABLE [PROJECT]
ADD FOREIGN KEY([CreatorId])
REFERENCES [USER]([Id])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [TEAM_MEMBER]
ADD FOREIGN KEY([UsedId])
REFERENCES [USER]([Id])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [TEAM_MEMBER]
ADD FOREIGN KEY([ProjectId])
REFERENCES [PROJECT]([Id])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [TEAM_MEMBER]
ADD FOREIGN KEY([ManagerId])
REFERENCES [USER]([Id])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [NOTIFICATION]
ADD FOREIGN KEY([RecieverId])
REFERENCES [USER]([Id])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [NOTIFICATION]
ADD FOREIGN KEY([SenderId])
REFERENCES [USER]([Id])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [TASK]
ADD FOREIGN KEY([CreatorId])
REFERENCES [USER]([Id])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [TASK]
ADD FOREIGN KEY([AssigneeId])
REFERENCES [USER]([Id])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [TASK]
ADD FOREIGN KEY([ParentTaskId])
REFERENCES [TASK]([Id])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [TASK]
ADD FOREIGN KEY([ProjectId])
REFERENCES [PROJECT]([Id])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [TASK_SEQUENCE]
ADD FOREIGN KEY([PreceedingTaskId])
REFERENCES [TASK]([Id])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [TASK_SEQUENCE]
ADD FOREIGN KEY([SubsequentTaskId])
REFERENCES [TASK]([Id])
ON UPDATE NO ACTION ON DELETE NO ACTION;
GO