//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOUPIShared.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceErrorMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SOUPIShared.Resources.ServiceErrorMessages", typeof(ServiceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действие с таким исполнителем, коммитом или сообщением уже существует .
        /// </summary>
        public static string ActivityAlreadyExists {
            get {
                return ResourceManager.GetString("ActivityAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действие не найдено.
        /// </summary>
        public static string ActivityNotFound {
            get {
                return ResourceManager.GetString("ActivityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назначение этого участника команды на эту задачу уже существует.
        /// </summary>
        public static string AssignmentAlreadyExists {
            get {
                return ResourceManager.GetString("AssignmentAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назначение не найдено  .
        /// </summary>
        public static string AssignmentNotFound {
            get {
                return ResourceManager.GetString("AssignmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь между задачами образует цикл .
        /// </summary>
        public static string JobCyclic {
            get {
                return ResourceManager.GetString("JobCyclic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата окончания задачи не может быть раньше или равна дате начала задачи .
        /// </summary>
        public static string JobIncompatibleEndStartDates {
            get {
                return ResourceManager.GetString("JobIncompatibleEndStartDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задача не найдена .
        /// </summary>
        public static string JobNotFound {
            get {
                return ResourceManager.GetString("JobNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прогресс задачи выходит за границы допустимого диапазона (0-100).
        /// </summary>
        public static string JobProgressOutOfRange {
            get {
                return ResourceManager.GetString("JobProgressOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задачи находятся на разных уровнях .
        /// </summary>
        public static string JobsDifferentLevels {
            get {
                return ResourceManager.GetString("JobsDifferentLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь между задачами уже существует.
        /// </summary>
        public static string JobSequenceAlreadyExists {
            get {
                return ResourceManager.GetString("JobSequenceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь между задачами образует цикл .
        /// </summary>
        public static string JobSequenceCyclic {
            get {
                return ResourceManager.GetString("JobSequenceCyclic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь между задачами не найдена .
        /// </summary>
        public static string JobSequenceNotFound {
            get {
                return ResourceManager.GetString("JobSequenceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь между задачами не существует в системе .
        /// </summary>
        public static string JobTitleNotUnique {
            get {
                return ResourceManager.GetString("JobTitleNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Родительская задача не найдена .
        /// </summary>
        public static string ParentJobNotFound {
            get {
                return ResourceManager.GetString("ParentJobNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проект с таким названием уже существует.
        /// </summary>
        public static string ProjectAlreadyExists {
            get {
                return ResourceManager.GetString("ProjectAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К этому проекту уже привязан репозиторий.
        /// </summary>
        public static string ProjectAlreadyHasRepository {
            get {
                return ResourceManager.GetString("ProjectAlreadyHasRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проект не найден .
        /// </summary>
        public static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этот репозиторий уже привязан к другому проекту .
        /// </summary>
        public static string RepositoryAlreadyLinkedToProject {
            get {
                return ResourceManager.GetString("RepositoryAlreadyLinkedToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректное название репозитория .
        /// </summary>
        public static string RepositoryNameNotValid {
            get {
                return ResourceManager.GetString("RepositoryNameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Участник команды не найден .
        /// </summary>
        public static string TeamMemberNotFound {
            get {
                return ResourceManager.GetString("TeamMemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь не найден .
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
